import fillpdf
from fillpdf import fillpdfs

input_pdf_path = '/Users/elias/Documents/GitHub/gasgate/gasgate/flask-server/CP16 (Gas Tightness-Purging-Strength) Master.pdf'
field_names = fillpdfs.get_form_fields(input_pdf_path, sort=False, page_number=None)


print(field_names)

data_dict = {'Text8': 'jobNum',
 'Text2': 'jobFullName', 
 'Text3': 'jobAddress', 
 'Text4': 'jobPostCode', 
 'Text5': 'jobContact', 
 'Text6': 'jobContactNum', 
 'Text7': 'gasSafeLicenseNum', 
 'Text9': 'fullName', 
 'Text10': 'positionHeld', 
 'Date11_af_date': '5/25/22', 
 'STRENGTH TEST DETAILSRow1': 'testMethod', 
 'STRENGTH TEST DETAILSRow2': 'N/A', 
 'STRENGTH TEST DETAILSRow3': 'N/A', 
 'STRENGTH TEST DETAILSRow4': 'N/A', 
 'STRENGTH TEST DETAILSRow5': 'N/A', 
 'STRENGTH TEST DETAILSRow6': 'N/A', 
 'STRENGTH TEST DETAILSRow7': 'N/A', 
 'STRENGTH TEST DETAILSRow8': 'N/A', 
 'STRENGTH TEST DETAILSRow9': 'N/A', 
 'STRENGTH TEST DETAILSRow10': 'N/A', 
 'STRENGTH TEST DETAILSRow11': 'N/A', 
 'STRENGTH TEST DETAILSRow12': 'N/A', 
 'TIGHTNESS TEST DETAILSRow1': 'N/A', 
 'TIGHTNESS TEST DETAILSRow2': 'N/A', 
 'TIGHTNESS TEST DETAILSRow3': 'N/A', 
 'TIGHTNESS TEST DETAILSRow4': 'N/A', 
 'TIGHTNESS TEST DETAILSRow5': 'N/A', 
 'TIGHTNESS TEST DETAILSRow6': 'N/A', 
 'TIGHTNESS TEST DETAILSRow7': 'N/A', 
 'TIGHTNESS TEST DETAILSRow8': 'N/A', 
 'TIGHTNESS TEST DETAILSRow9': 'N/A', 
 'TIGHTNESS TEST DETAILSRow10': 'N/A', 
 'TIGHTNESS TEST DETAILSRow11': 'N/A', 
 'TIGHTNESS TEST DETAILSRow12': 'N/A', 
 'TIGHTNESS TEST DETAILSRow13': 'N/A', 
 'TIGHTNESS TEST DETAILSRow14': 'N/A', 
 'TIGHTNESS TEST DETAILSRow15': 'N/A', 
 'TIGHTNESS TEST DETAILSRow16': 'N/A', 
 'TIGHTNESS TEST DETAILSRow17': 'N/A', 
 'TIGHTNESS TEST DETAILSRow18': 'N/A', 
 'TIGHTNESS TEST DETAILSRow19': 'N/A', 
 'TIGHTNESS TEST DETAILSRow20': 'N/A', 
 'TIGHTNESS TEST DETAILSRow21': 'N/A', 
 'TIGHTNESS TEST DETAILSRow22': 'N/A', 
 'TIGHTNESS TEST DETAILSRow23': 'N/A', 
 'PURGING PROCEDURE DETAILSRow1': 'N/A', 
 'PURGING PROCEDURE DETAILSRow2': 'N/A', 
 'PURGING PROCEDURE DETAILSRow3': 'N/A', 
 'PURGING PROCEDURE DETAILSRow4': 'N/A', 
 'PURGING PROCEDURE DETAILSRow5': 'N/A', 
 'PURGING PROCEDURE DETAILSRow6': 'N/A', 
 'PURGING PROCEDURE DETAILSRow7': 'N/A', 
 'PURGING PROCEDURE DETAILSRow8': 'N/A', 
 'PURGING PROCEDURE DETAILSRow9': 'N/A', 
 'PURGING PROCEDURE DETAILSRow10': 'N/A', 
 'PURGING PROCEDURE DETAILSRow11': 'N/A', 
 'PURGING PROCEDURE DETAILSRow12': 'N/A', 
 'PURGING PROCEDURE DETAILSRow13': 'N/A', 
 'FindingsRow1': 'N/A', 
 'FindingsRow2': 'N/A', 
 'Text1': '', 
 'ste test': '', 
 'purge': '', 
 'tightness test': '', 
 'Form given to': '', 
 'Check Box21': '', 
 'Check Box22': '', 
 'Signature16': '', 
 'Signature17': '', 
 'Signature18': '', 
 'Signature19': ''
}

fillpdfs.write_fillable_pdf(input_pdf_path, 'test.pdf', data_dict)