import fillpdf
from fillpdf import fillpdfs

input_pdf_path = '/Users/elias/Documents/GitHub/gasgate/gasgate/flask-server/CP15(CommericalServicing)Master.pdf'
field_names = fillpdfs.get_form_fields(input_pdf_path, sort=False, page_number=None)


print(field_names)

data_dict = {
    'Job': '', 
    'Name': '', 
    'Address': '', 
    'Post Code': '', 
    'Site Contact': '', 
    'Contact No': '', 
    '520592Gas Safe Card Serial No': '', 
    '520592Engineer Name': '', 
    '520592Position Held': '', 
    'Dateofwork_af_date': '', 
    'Unit 1 name': '', 
    'No1Location': '', 
    'No1Boiler Type': '', 
    'No1Boiler Model': '', 
    'No1Boiler Serial No': '', 
    'No1Burner manufacturer ModelSerialif different': '', 
    'No1Flue type': '', 
    'Date1': '', 
    'Date2': '', 
    'Maximum Operating Pressure of Boiler Bar': '', 
    'Unit 2 name': '', 
    'Appliance STU 1': '', 
    'No2Location': 'N/A', 
    'No2Boiler Type': 'N/A', 
    'No2Boiler Model': 'N/A', 
    'No2Boiler Serial No': 'N/A', 
    'No2Burner manufacturer ModelSerialif different': 'N/A', 
    'No2Flue type': 'N/A', 
    '2Date1': 'N/A', 
    '2Date2': 'N/A', 
    'Maximum Operating Pressure of Boiler Bar2': 'N/A', 
    'Appliance STU 2': '', 
    'Unit 3 name': '', 
    'No3Location': 'N/A', 
    'No3Boiler Type': 'N/A', 
    'No3Boiler Model': 'N/A', 
    'No3Boiler Serial No': 'N/A', 
    'No3Burner manufacturer ModelSerialif different': 'N/A', 
    'No3Flue type': 'N/A', 
    '3Date1': 'N/A', 
    '3Date2': 'N/A', 
    'Maximum Operating Pressure of Boiler Bar3': 'N/A', 
    'Appliance STU 3': '', 
    'LowHeat input rating kW': '', 
    'LowGas burner pressure mbar': '', 
    'LowGas rate m3hr': '', 
    'LowAirgas ratio control setting': '', 
    'LowAmbient room temperature o C': '', 
    'Lowo Flue Gas temperature gross  C': '', 
    'Lowo Flue Gas temperature net  C': '', 
    'LowFlue draught pressure mbar': '', 
    'LowOxygen O2': '', 
    'LowCarbon monoxide CO ppm': '', 
    'LowCarbon dioxide CO2': '', 
    'LowNOx': '', 
    'LowExcess air': '', 
    'LowCOCO2 Ratio': '', 
    'LowGross efficiency': '', 
    'LowCO flue dilution ppm': '', 
    'HighHeat input rating kW': '', 
    'HighGas burner pressure mbar': '', 
    'HighGas rate m3hr': '', 
    'HighAirgas ratio control setting': '', 
    'HighAmbient room temperature o C': '', 
    'Higho Flue Gas temperature gross  C': '', 
    'Higho Flue Gas temperature net  C': '', 
    'HighFlue draught pressure mbar': '', 
    'HighOxygen O2': '', 
    'HighCarbon monoxide CO ppm': '', 
    'HighCarbon dioxide CO2': '', 
    'HighNOx': '', 
    'HighExcess air': '', 
    'HighCOCO2 Ratio': '', 
    'HighGross efficiency': '', 
    'HighCO flue dilution ppm': '', 
    'LowHeat input rating kW_2': 'N/A', 
    'LowGas burner pressure mbar_2': 'N/A', 
    'LowGas rate m3hr_2': 'N/A', 
    'LowAirgas ratio control setting_2': 'N/A', 
    'LowAmbient room temperature o C_2': 'N/A', 
    'Lowo Flue Gas temperature gross  C_2': 'N/A', 
    'Lowo Flue Gas temperature net  C_2': 'N/A', 
    'LowFlue draught pressure mbar_2': 'N/A', 
    'LowOxygen O2_2': 'N/A', 
    'LowCarbon monoxide CO ppm_2': 'N/A', 
    'LowCarbon dioxide CO2_2': 'N/A', 
    'LowNOx_2': 'N/A', 
    'LowExcess air_2': 'N/A', 
    'LowCOCO2 Ratio_2': 'N/A', 
    'LowGross efficiency_2': 'N/A', 
    'LowCO flue dilution ppm_2': 'N/A', 
    'HighHeat input rating kW_2': 'N/A', 
    'HighGas burner pressure mbar_2': 'N/A', 
    'HighGas rate m3hr_2': 'N/A', 
    'HighAirgas ratio control setting_2': 'N/A', 
    'HighAmbient room temperature o C_2': 'N/A', 
    'Higho Flue Gas temperature gross  C_2': 'N/A', 
    'Higho Flue Gas temperature net  C_2': 'N/A', 
    'HighFlue draught pressure mbar_2': 'N/A', 
    'HighOxygen O2_2': 'N/A', 
    'HighCarbon monoxide CO ppm_2': 'N/A', 
    'HighCarbon dioxide CO2_2': 'N/A', 
    'HighNOx_2': 'N/A', 
    'HighExcess air_2': 'N/A', 
    'HighCOCO2 Ratio_2': 'N/A', 
    'HighGross efficiency_2': 'N/A', 
    'HighCO flue dilution ppm_2': 'N/A', 
    'LowHeat input rating kW_3': 'N/A', 
    'LowGas burner pressure mbar_3': 'N/A', 
    'LowGas rate m3hr_3': 'N/A', 
    'LowAirgas ratio control setting_3': 'N/A', 
    'LowAmbient room temperature o C_3': 'N/A', 
    'Lowo Flue Gas temperature gross  C_3': 'N/A', 
    'Lowo Flue Gas temperature net  C_3': 'N/A', 
    'LowFlue draught pressure mbar_3': 'N/A', 
    'LowOxygen O2_3': 'N/A', 
    'LowCarbon monoxide CO ppm_3': 'N/A', 
    'LowCarbon dioxide CO2_3': 'N/A', 
    'LowNOx_3': 'N/A', 
    'LowExcess air_3': 'N/A', 
    'LowCOCO2 Ratio_3': 'N/A', 
    'LowGross efficiency_3': 'N/A', 
    'LowCO flue dilution ppm_3': 'N/A', 
    'HighHeat input rating kW_3': 'N/A', 
    'HighGas burner pressure mbar_3': 'N/A', 
    'HighGas rate m3hr_3': 'N/A', 
    'HighAirgas ratio control setting_3': 'N/A', 
    'HighAmbient room temperature o C_3': 'N/A', 
    'Higho Flue Gas temperature gross  C_3': 'N/A', 
    'Higho Flue Gas temperature net  C_3': 'N/A', 
    'HighFlue draught pressure mbar_3': 'N/A', 
    'HighOxygen O2_3': 'N/A', 
    'HighCarbon monoxide CO ppm_3': 'N/A', 
    'HighCarbon dioxide CO2_3': 'N/A', 
    'HighNOx_3': 'N/A', 
    'HighExcess air_3': 'N/A', 
    'HighCOCO2 Ratio_3': 'N/A', 
    'HighGross efficiency_3': 'N/A', 
    'HighCO flue dilution ppm_3': 'N/A', 
    'Flue flow test satisfactory': '', 
    'Spillage test satisfactory': '', 
    'Ventilation satisfactory see also General safety checks': '', 
    'Airgas pressure switch operating correctly': '', 
    'Flame providingsafety devices operating correctly': '', 
    'Burner lockout time seconds': '', 
    'Temperature and limit thermostats operating correctly': '', 
    'Appliance serviced': '', 
    'Standing pressure Gas Mbar': '', 
    'Working gas pressure all boilers run Mbar': '', 
    'Gas line diagram in place': '', 
    'Flue flow test satisfactory2': 'N/A', 
    'Spillage test satisfactory2': 'N/A', 
    'Ventilation satisfactory see also General safety checks2': 'N/A', 
    'Airgaspressureswtich2': 'N/A', 
    'Flame providingsafety devices operating correctly2': 'N/A', 
    'Burner lockout time seconds2': 'N/A', 
    'Temperature and limit thermostats operating correctly2': 'N/A', 
    'Appliance serviced2': 'N/A', 
    'Standing pressure Gas Mbar2': 'N/A', 
    'Working gas pressure all boilers run Mbar2': 'N/A', 
    'Gas line diagram in place2': 'N/A', 
    'Flue flow test satisfactory3': 'N/A', 
    'Spillage test satisfactory3': 'N/A', 
    'Ventilation satisfactory see also General safety checks3': 'N/A', 
    'Airgas pressure switch operating correctly3': 'N/A', 
    'Flame providingsafety devices operating correctly3': 'N/A', 
    'Burner lockout time seconds3': 'N/A', 
    'Temperature and limit thermostats operating correctly3': 'N/A', 
    'Appliance serviced3': 'N/A', 
    'Standing pressure Gas Mbar3': 'N/A', 
    'Working gas pressure all boilers run Mbar3': 'N/A', 
    'Gas line diagram in place3': 'N/A', 
    'Gas boosterscompressorss operating correctly': '', 
    'Gas tightness test': 'Local', 
    'Gas installation pipework adequately supported': '', 
    'Gas installation pipework sleevedlabelledpainted as necessary': '', 
    'Flue system installed in accordance with appropriate standards': '', 
    'Flue route inc voids  termination satisfactory': '', 
    'Fanflue interlock operating correctly': '', 
    'Ventilation Type': '', 
    '1 Plant roomcompartment ventilation lowlevel free area cm2': '', 
    'Highlevel free area cm 2': '', 
    '2 Mechanical ventilation flow rate inlet m3s': '', 
    'extract m3s': '', 
    'Mechanical ventilation interlock operating correctly': '', 
    'Is ventilation satisfactory YesNo if no see Details of remedial work required': '', 
    'Details of work carried out  Remedial WorkRow1': '', 
    'MakeNo1': '', 
    'FigUseNo1': '', 
    'DNNo1': '', 
    'BarNo1': '', 
    'PRVDate1': '', 
    'MakeNo2': 'N/A', 
    'FigUseNo2': 'N/A', 
    'DNNo2': 'N/A', 
    'BarNo2': 'N/A', 
    'PRVDate2': 'N/A', 
    'MakeNo3': 'N/A', 
    'FigUseNo3': 'N/A', 
    'DNNo3': 'N/A', 
    'BarNo3': 'N/A', 
    'PRVDate3': 'N/A', 
    'Manufacturer': 'N/A', 
    'Model': 'N/A', 
    'Serial No': 'N/A', 
    'BoosterDate1': 'N/A', 
    'No1Maximum Inlet Pressure mbar': 'N/A', 
    'No1Maximum Pressure Lift mbar': 'N/A', 
    'No1Maximum Outlet Pressure mbar': 'N/A', 
    'No1Low pressure cutoff devices operating': 'N/A', 
    'No1Minimum setting of 10mbar': 'N/A', 
    'Booster Safe 1': '', 
    'Manufacturer2': 'N/A', 
    'Model2': 'N/A', 
    'Serial No2': 'N/A', 
    'BoosterDate2': 'N/A', 
    'No2Maximum Inlet Pressure mbar': 'N/A', 
    'No2Maximum Pressure Lift mbar': 'N/A', 
    'No2Maximum Outlet Pressure mbar': 'N/A', 
    'No2Low pressure cutoff devices operating': 'N/A', 
    'No2Minimum setting of 10mbar': 'N/A', 
    'Booster Safe 2': '', 
    'Manufacturer3': 'N/A', 
    'Model3': 'N/A', 
    'Serial No3': 'N/A', 
    'BoosterDate3': 'N/A', 
    'No3Maximum Inlet Pressure mbar': 'N/A', 
    'No3Maximum Pressure Lift mbar': 'N/A', 
    'No3Maximum Outlet Pressure mbar': 'N/A', 
    'No3Low pressure cutoff devices operating': 'N/A', 
    'No3Minimum setting of 10mbar': 'N/A', 
    'Booster Safe 3': '', 
    'Has a warningadvice notice been raised': '', 
    'Has a warning labels been attached': '', 
    'Has responsible person been advised': '', 
    'Warning notice ID Numberif applicable GP14': ''
}
